### ISSUE TITLE
Build Issue with -lgomp flag

### ISSUE THREAD

**Issue by shosty** [msmbuilder/msmbuilder-legacy#370]
Hi! I'm trying to install MSMbuilder2.7.0 on our dept. linux cluster, using the --prefix installation flag, and continue getting the following error when attempting to install:

> > error: Command "gcc -pthread -shared build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src/ext/asa/_asamodule.o build/temp.linux-x86_64-2.7/src/ext/asa/asa.o build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortranobject.o -lgomp -o build/lib.linux-x86_64-2.7/msmbuilder/_asa.so" failed with exit status 1

However, if I try executing the faulty command on its own (from the command line) it compiles and produces _asa.so correctly. I think there is a problem with some linked libraries but I can't figure out why it works fine on its own but not during install. 

Here's some more info on the machine:

> > python
> > Python 2.7.3 (default, Mar 19 2013, 12:42:39) 
> > [GCC 4.4.5 20110214 (Red Hat 4.4.5-6)] on linux2
> > Type "help", "copyright", "credits" or "license" for more information.
> > 
> > echo $PATH
> > /net/antonin/home/chakra/savol/local/bin:/csb/sl64/torque/bin:/csb/sl64/torque/sbin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/net/antonin/home/chakra/savol/bin
> > 
> > echo $PYTHONPATH
> > /net/antonin/usr/local/anaconda/lib/python2.7/site-packages:/net/antonin/home/chakra/savol/lib/python2.7/site-packages

echo $LD_LIBRARY_PATH 
/csb/sl64/torque/lib:/usr/lib/gcc/x86_64-redhat-linux/4.4.4/

I added usr/lib/gcc/x86_64-redhat-linux/4.4.4/ to the LD_LIBRARY_PATH because the gomp libraries are located there and executing the offending command from the command line >> gcc -pthread -shared ..... /msmbuilder/_asa.so
failed unless either $PATH or $LD_LIBRARY_PATH pointed there. Using -L also worked but I don't know how to tell the install compilation to add the linked library to gcc commands. Likewise, >> alias gcc="gcc -L/usr/lib/gcc/x86_64-redhat-linux/4.4.4/" worked at the command line but didn't prevent the compilation error during install.

Any suggestions for this install error would be much appreciated. Many thanks!
